blueprint:
  name: Carbon Monoxide Alarm Triggered
  description: Set the actions to take when a carbon monoxide alarm is triggered
  domain: automation
  source_url: https://github.com/EffortlessHome/blueprints/blob/main/eh_co_alarm.yaml
  input:
    carbonmonoxidealarm:
      name: Carbon Monoxide Alarm Sensor
      description: The triggering carbon monoxide alarm sensor(s)
      selector:
        entity:
          filter:
          - domain:
            - binary_sensor
          multiple: true
    additional_actions:
      name: Additional Actions After
      description: Add additional actions to the script. Will execute after everything.
        (optional) else.
      default: []
      selector:
        action: {}
trigger:
- platform: state
  entity_id: !input carbonmonoxidealarm
  to: 'on'
action:
- service: notify.notify
  data:
    message: Carbon Monoxide Alarm Activated. Get to Safety and Check for CO immediately.
- choose: []
  default: !input additional_actions