blueprint:
  name: Camera Custom Motion Detection
  description: Camera Custom Motion Detection
  domain: automation
  author: EffortlessHome
  source_url: https://github.com/EffortlessHome/blueprints/blob/main/eh_camera_custom_motion.yaml
  input:
    motion_entity:
    name: Motion Sensor
    selector:
      entity:
        filter:
        - device_class:
          - motion
          domain:
          - binary_sensor
        multiple: false
    goodnightranforday:
      name: goodnightranforday
      description: goodnightranforday
      selector:
        entity:
          filter:
          - domain:
            - input_boolean
          multiple: false

trigger:
- at: input_datetime.paramgoodmorningtime
  platform: time
condition:
- condition: state
  entity_id: !input issomeonehome
  state: 'on'
action:
- service: alarmo.disarm
  data:
    entity_id: !input securityalarm
- service: input_boolean.turn_off
  target:
    entity_id: !input goodnightranforday
