blueprint:
  name: Camera Motion Detected
  description: Camera Motion Detected
  domain: automation
  author: EffortlessHome
  source_url: https://github.com/EffortlessHome/blueprints/blob/main/eh_camera_motion.yaml
  input:
    motion_entity:
      name: Camera Motion Sensor
      selector:
        entity:
          filter:
          - device_class:
            - motion
            domain:
            - binary_sensor
          multiple: false  
    cameraname:
      name: cameraname
      description: The name of the camera (don't use spaces or special characters)
      selector:
        entity:
          filter:
          - domain:
            - input_text
          multiple: false

trigger:
  platform: state
    entity_id:
      - !input motion_entity
    to: "on"
condition: []
action:
 - variables:
      motionimagefilename: "{{ now().strftime(\"%Y%m%d-%H%M%S\") }}.jpg"
- service: camera.snapshot
  data:
    filename: /media/motion/{{!input cameraname}}/{{motionimagefilename}}
  target:
    entity_id: camera.doorbellcam1_fluent
- service: input_boolean.turn_off
  target:
    entity_id: !input goodnightranforday
