blueprint:
  name: Determine if Someone is in the Home Zone
  description: Determine if Someone is in the Zone using Person entities and other devices
  domain: automation
  author: EffortlessHome
  source_url: https://github.com/EffortlessHome/blueprints/blob/main/eh_determine_if_someone_at_homezone.yaml
  input:
      zone_input:
          name: Zone
          description: Select a zone to monitor
          default: "zone.home"
          selector:
              entity:
                  filter:
                      domain: zone
      person_input:
          name: Entities with location
          description: Select entities to track
          selector:
              entity:
                  multiple: true
                  filter:
                      domain: person

      additional_conditions:
          name: Conditions
          default: []
          description: Any additional conditions
          selector:
              condition:


variables:
  person_list_variable: !input person_input
  zone_variable: !input zone_input

trigger:
    platform: state
    entity_id: !input zone_input

condition:
    - and: !input additional_conditions
    - alias: Internal logic
      condition: not
      conditions:
          - condition: template
            value_template: '{{ (person_list_variable + state_attr(zone_variable, "persons")) | count != dict.fromkeys(person_list_variable + state_attr(zone_variable, "persons")) | count }}'

action:
- service: input_boolean.turn_on
  data: {}
  entity_id: input_boolean.issomeonehome

mode: single
