blueprint:
  name: Determine if someone is at home using motion sensors
  description: Determine if someone is at home using motion sensors
  domain: automation
  author: EffortlessHome
  source_url: https://github.com/EffortlessHome/blueprints/blob/main/eh_determine_if_someone_is_home_with_sensors.yaml
  input:
     motion_entity:
        name: Motion Sensor(s)
        selector:
          entity:
            domain:
            - binary_sensor
            device_class:
            - motion
            multiple: true

trigger:
  platform: state
  entity_id: !input motion_entity
  to: "on"
action:
- service: input_boolean.turn_on
  target:
    entity_id: input_boolean.issomeonehome

mode: single
