blueprint:
  name: Follow Me Music Occupy
  description: Actions to take when the follow me music mode is on and the area is occupied
  domain: automation
  author: EffortlessHome
  source_url: https://raw.githubusercontent.com/EffortlessHome/blueprints/main/eh_follow_me_music_occupy.yaml
  input:
    motion_entity:
      name: Motion Sensor(s)
      selector:
        entity:
          domain:
          - binary_sensor
          device_class:
          - motion
          multiple: true
    media_player:
      name: Media Player(s)
      selector:
        entity:
          domain:
          - media_player
          multiple: true
    volume_level:
      description: The volume level to set
      name: Volume Level
      default: 0.5
      selector:
        number:
          min: 0.0
          max: 1.0
          step: 0.1
          mode: slider
    additional_actions:
      name: Additional Actions After
      description: Add additional actions to the script. Will execute after everything.
        (optional) else.
      default: []
      selector:
        action: {}
trigger:
- platform: state
  entity_id: !input motion_entity
  to: "on"
condition:
- condition: state
  entity_id: !input media_player
  state: playing
- condition: state
  entity_id: input_boolean.followmemusicmode
  state: "on"
action:
- service: media_player.volume_set
  entity_id: !input media_player
  data:
    volume_level: !input volume_level
- choose: []
  default: !input additional_actions
