blueprint:
  name: Good Morning
  description: At morning, disarm alarm, enable person detection, stop sleeping setting
  domain: automation
  author: EffortlessHome
  source_url: https://raw.githubusercontent.com/EffortlessHome/blueprints/main/eh_goodmorning.yaml
  input:
    goodnightranforday:
      name: goodnightranforday
      description: goodnightranforday
      selector:
        entity:
          filter:
          - domain:
            - input_boolean
          multiple: false
    goodmorning_time:
      name: What time of the day will goodmorning run
      description: The time of day when this will run each day.
      selector:
        time: {}
    issomeonehome:
      name: issomeonehome
      description: issomeonehome
      selector:
        entity:
          filter:
          - domain:
            - input_boolean
          multiple: false
    securityalarm:
      name: Security Alarm
      description: The security alarm to disable
      selector:
        entity:
          filter:
          - domain:
            - alarm_control_panel
          multiple: false
    additional_actions:
      name: Additional Actions After
      description: Add additional actions to the script. Will execute after everything
        else.
      default: []
      selector:
        action: {}
trigger:
- at: !input goodmorning_time
  platform: time
  enabled: true
condition:
- condition: state
  entity_id: !input issomeonehome
  state: 'on'
action:
- service: alarmo.disarm
  data:
    entity_id: !input securityalarm
- service: input_boolean.turn_off
  target:
    entity_id: !input goodnightranforday
- choose: []
  default: !input additional_actions
