blueprint:
  name: Goodnight
  description: Actions to take when going to bed for the night
  domain: automation
  author: EffortlessHome
  source_url: https://raw.githubusercontent.com/EffortlessHome/blueprints/main/eh_goodnight.yaml
  input:
    goodnightranforday:
      name: goodnightranforday
      description: goodnightranforday
      selector:
        entity:
          filter:
          - domain:
            - input_boolean
          multiple: false
    lighttoturnon:
      name: Lights to turn on
      description: Turn on these lights (optional)
      default: {}
      selector:
        entity:
          filter:
          - domain:
            - light
          multiple: true
    garagedoor:
      name: The garage door
      description: Close this garage door (optional)
      default: {}      
      selector:
        entity:
          filter:
          - domain:
            - cover
          multiple: true
    securityalarm:
      name: Security Alarm
      description: The security alarm to disable
      selector:
        entity:
          filter:
          - domain:
            - alarm_control_panel
          multiple: false
    doorlock:
      name: Door Lock
      description: The door lock to lock
      default: {}      
      selector:
        entity:
          filter:
          - domain:
            - lock
          multiple: false
    plugtoturnoff:
      name: Plugs to turn off
      description: Turn off these plugs (optional)
      default: {}      
      selector:
        entity:
          filter:
          - domain:
            - switch
          multiple: true
    lighttoturnoff:
      name: Lights to turn off
      description: Turn off these lights (optional)
      default: {}      
      selector:
        entity:
          filter:
          - domain:
            - light
          multiple: true
    additional_actions:
      name: Additional Actions After
      description: Add additional actions to the script. Will execute after everything. (optional)
        else.
      default: []
      selector:
        action: {}          

condition:
- condition: state
  entity_id: !input goodnightranforday
  state: 'off'
action:
- service: input_boolean.turn_on
  target:
    entity_id: !input goodnightranforday
- service: light.turn_on
  target:
    entity_id:
    - !input lighttoturnon
- service: alarmo.arm
  data:
    mode: home
    skip_delay: false
    force: false
    entity_id: !input securityalarm
- service: switch.turn_off
  target:
    entity_id: !input plugtoturnoff
- service: lock.lock
  target:
    entity_id: !input doorlock
- service: cover.close_cover
  target:
    entity_id: !input garagedoor

- choose: []
  default: !input additional_actions
