blueprint:
  name: Leave Home
  description: Actions to take when leaving home and no one left at home
  domain: automation
  author: EffortlessHome
  source_url: https://github.com/EffortlessHome/blueprints/blob/main/eh_leavehome.yaml
  input:
    issomeonehome:
      name: issomeonehome
      description: The issomeonehome flag to use to determine if anyone remains at home
      selector:
        entity:
          filter:
          - domain:
            - input_boolean
          multiple: false
    securityalarm:
      name: Security Alarm
      description: The security alarm to disable
      selector:
        entity:
          filter:
          - domain:
            - alarm_control_panel
          multiple: false

    lightgroup:
      name: Light Group
      description: The Light Group To Turn Off. Recommend creating a group called "All Lights" and using that.
      selector:
        entity:
          filter:
          - domain:
            - light
          multiple: false          
trigger:
- platform: state
  entity_id:
    - input_boolean.issomeonehome
  from: "on"
  to: "off"
  for:
    hours: 0
    minutes: 5
    seconds: 0
condition: []
action:
- service: alarmo.disarm
  data:
    entity_id: !input securityalarm
    mode: away
- service: light.turn_off
  target:
    entity_id: !input lightgroup
- service: switch.turn_on
  target:
    entity_id: switch.simulatepresencewhenaway
