blueprint:
  name: Smoke Alarm Triggered
  description: Set the actions to take when a smoke alarm is triggered
  domain: automation
  source_url: https://github.com/EffortlessHome/blueprints/blob/main/eh_smoke_alarm.yaml
  input:
    smokealarm:
      name: Smoke Alarm Sensor
      description: The triggering smoke alarm sensor(s)
      selector:
        entity:
          filter:
          - domain:
            - binary_sensor
          multiple: true
trigger:
- platform: state
  entity_id: !input smokealarm
  to: 'on'
action:
- service: notify.notify
  data:
    message: Smoke Alarm Activated. Check for fire immediately.
