blueprint:
  name: Water Alarm Triggered
  description: Set the actions to take when a water alarm is triggered
  domain: automation
  source_url: https://github.com/EffortlessHome/blueprints/blob/main/eh_water_alarm.yaml
  input:
    watersensor:
      name: Water Leak Sensor
      description: The triggering water leak sensor
      selector:
        entity:
          filter:
          - domain:
            - binary_sensor
          multiple: false
    stopwaterswitch:
      name: The Stop Water Switch
      description: Turn on the stop water switch
      default: {}
      selector:
        entity:
          filter:
          - domain:
            - switch
          multiple: false
 
trigger:
- platform: state
  entity_id:
  - !input watersensor
  to: 'on'
action:
- service: notify.notify
  data:
    message: Water Sensor Activated. Check for water immediately.
- service: switch.turn_on
  target:
    entity_id: !input stopwaterswitch

