blueprint:
  name: Camera Motion
  description: This automation blueprint creates a camera snapshot if motion is detected,
    or if a binary sensor's state turns 'off' to 'on', and sends a notification to
    your phone with the picture. Clicking the navigation will navigate to dashboard
    URL. Extends/customizes the work of https://gist.githubusercontent.com/TheRealFalseReality/eab315e84f2711783fb7454ac0b42187/raw/dab98ed49497432aa85f11d6727ba2c5c6397d3d/send_snapshot_conditional.yaml
  domain: automation
  author: EffortlessHome
  source_url: https://github.com/EffortlessHome/blueprints/raw/refs/heads/main/automation/EffortlessHome/eh_camera_motion.yaml
  input:
    sensor:
      name: Motion or Binary Sensor
      description: The sensor wich triggers the snapshot creation
      selector:
        entity:
          domain:
          - binary_sensor
          multiple: false
    camera:
      name: Camera
      description: The camera which creates the snapshot
      selector:
        entity:
          domain:
          - camera
          multiple: false
    file_path:
      name: File Path
      description: The file path to store the most current snapshot. Defaults to **/media/snapshots/<camera_name>**
        - `/media/snapshots/{{ states[camera].object_id }}/last_motion.jpg`.
      default: /media/snapshots/{{ states[camera].object_id }}/last_motion.jpg
    notification_title:
      name: Notification title
      description: 'Default: "Motion detected!"'
      default: Motion detected!
    notification_message:
      name: Notification message
      description: 'Default: "{{ sensor_name }} detected movement! Snapshot from {{
        camera_name }} at {{ time }}."'
      default: '{{ sensor_name }} detected movement! Snapshot from {{ camera_name
        }} at {{ time }}.'
    data_clickaction_url:
      name: URL to Navigate (Optional)
      description: The URL to navigate to when clicking on the notification. (default
        = /lovelace)
      default: /lovelace
    additional_actions:
      name: Additional Actions After
      description: Add additional actions to the script. Will execute after everything
        else.
      default: []
      selector:
        action: {}
    action_type:
      name: Action Type (EXPERIMENTAL)
      description: 'Set action type, see [Actionable Notifications](https://companion.home-assistant.io/docs/notifications/actionable-notifications/).
        default: URI'
      default: URI
    action_title:
      name: Action Title (EXPERIMENTAL)
      description: Title of action that will appear with the notification
      default: Open Dashboard
    action_uri:
      name: Action URI (EXPERIMENTAL)
      description: 'URI to naviagte to. default: /lovelace'
      default: '{{ clickActionURL }}'
trigger:
- platform: state
  entity_id: !input sensor
  from: 'off'
  to: 'on'
variables:
  sensor: !input sensor
  sensor_name: '{{ states[sensor].name }}'
  camera: !input camera
  camera_name: '{{ states[camera].name }}'
  time: '{{ now().strftime("%H:%M") }}'
  date: '{{ now().strftime("%Y-%m-%d") }}'
  notification_title: !input notification_title
  notification_message: !input notification_message
  file_path: /media/snapshots/{{ states[camera].object_id }}/last_motion.jpg
  archive_file_path: /media/snapshots/{{ states[camera].object_id }}/archive/motion/{{
    now().strftime("%Y%m%d-%H%M%S") }}.jpg
  snapshot_create_file_path: !input file_path
  snapshot_access_file_path: '{{ snapshot_create_file_path | replace(''/media'',''/media/local'')
    }}'
  clickActionURL: !input data_clickaction_url
  additional_actions: !input additional_actions
  action_type: !input action_type
  action_title: !input action_title
  action_uri: !input action_uri
action:
- service: camera.snapshot
  entity_id: !input camera
  data:
    filename: !input file_path
- service: notify.notify
  data:
    title: !input notification_title
    message: !input notification_message
    data:
      image: '{{ snapshot_access_file_path }}'
      clickAction: !input data_clickaction_url
      ttl: 0
      priority: high
      attachment:
        url: '{{ snapshot_access_file_path }}'
        content_type: JPEG
      url: !input data_clickaction_url
      actions:
      - action: '{{ action_type }}'
        title: '{{ action_title }}'
        uri: '{{ action_uri }}'
- service: camera.snapshot
  entity_id: !input camera
  data:
    filename: '{{ archive_file_path }}'
- choose: []
  default: !input additional_actions
mode: parallel
