blueprint:
  name: Motion and Person Image File Cleanup
  description: Daily cleanup of 30+ day old motion and person detection image files
  domain: automation
  author: EffortlessHome
  input:
    execution_time:
      name: What time of the day will this cleanup run
      description: The time of day when this will run each day.
      selector:
        time: {}
trigger:
- at: !input execution_time
  platform: time
action:
- service: shell_command.move_motion_files
  data: {}
