blueprint:
  name: Sunset
  description: Actions to take when the sun sets (e.g. turn on certain lights) if
    someone is home
  domain: automation
  author: EffortlessHome
  source_url: https://github.com/EffortlessHome/blueprints/raw/refs/heads/main/automation/EffortlessHome/eh_sunset.yaml
  input:
    lighttoturnon:
      name: Lights to turn on
      description: Turn on these lights (optional)
      default: []
      selector:
        target:
          entity:
          - domain:
            - light
            - switch
    plugtoturnon:
      name: Plugs to turn on
      description: Turn on these plugs (optional)
      default: []
      selector:
        entity:
          filter:
          - domain:
            - switch
          multiple: true
    additional_actions:
      name: Additional Actions After
      description: Add additional actions to the script. Will execute after everything.
        (optional) else.
      default: []
      selector:
        action: {}
trigger:
  - platform: sun
    event: sunset
    offset: 0
condition:
- condition: state
  entity_id: binary_sensor.someone_home_sensor
  state: 'On'
action:
- service: light.turn_on
  target:
    entity_id: !input lighttoturnon
- service: switch.turn_on
  target:
    entity_id: !input plugtoturnon
- choose: []
  default: !input additional_actions
