blueprint:
  name: Temperature Alarm Triggered
  description: Set the actions to take when a temperature alarm is triggered
  domain: automation
  author: EffortlessHome
  source_url: https://github.com/EffortlessHome/blueprints/raw/refs/heads/main/automation/EffortlessHome/eh_temperature_alarm.yaml
  input:
    tempsensor:
      name: Temperature Sensor
      description: The triggering temperature sensor(s)
      selector:
        entity:
          filter:
          - domain:
            - sensor
            - group
          multiple: true
    low_trigger_temperature:
      description: Temperature to use to trigger a low temp alert
      name: Low temperature trigger
      default: 40
      selector:
        number:
          min: 0.0
          max: 60.0
          unit_of_measurement: degrees
          step: 1.0
          mode: slider
    high_trigger_temperature:
      description: Temperature to use to trigger a high temp alert
      name: High temperature trigger
      default: 85
      selector:
        number:
          min: 0.0
          max: 99.0
          unit_of_measurement: degrees
          step: 1.0
          mode: slider
    notification_message:
      name: Notification message
      description: 'Temperature Sensor Activated Message'
      default: 'Temperature Sensor Activated'
    additional_actions:
      name: Additional Actions
      description: Add additional actions to the script. Will execute after everything
        else.
      default: []
      selector:
        action: {}
    data_clickaction_url:
      name: URL to Navigate (Optional)
      description: The URL to navigate to when clicking on the notification. (default
        = /lovelace)
      default: /lovelace
    action_type:
      name: Action Type (EXPERIMENTAL)
      description: 'Set action type, see [Actionable Notifications](https://companion.home-assistant.io/docs/notifications/actionable-notifications/).
        default: URI'
      default: URI
    action_title:
      name: Action Title (EXPERIMENTAL)
      description: Title of action that will appear with the notification
      default: Open Dashboard
    action_uri:
      name: Action URI (EXPERIMENTAL)
      description: 'URI to naviagte to. default: /lovelace'
      default: '{{ clickActionURL }}'
trigger:
- platform: numeric_state
  entity_id: !input tempsensor
  above: !input high_trigger_temperature
- platform: numeric_state
  entity_id: !input tempsensor
  below: !input low_trigger_temperature
variables:
  clickActionURL: !input data_clickaction_url
  action_type: !input action_type
  action_title: !input action_title
  action_uri: !input action_uri
action:
- service: notify.notify
  data:
    title: Temperature Sensor Activated
    message: !input notification_message
    data:
      clickAction: !input data_clickaction_url
      ttl: 0
      priority: high
      url: !input data_clickaction_url
      actions:
      - action: '{{ action_type }}'
        title: '{{ action_title }}'
        uri: '{{ action_uri }}'
- choose: []
  default: !input additional_actions
